import json
import re

with open('tenant_all_with_username.json', encoding='utf-8') as f:
    tenants = json.load(f)

def php_str(s):
    if not s:
        return ''
    return s.replace("\\", "\\\\").replace("'", "\\'")

lines = []
lines.append('<?php')
lines.append('')
lines.append('namespace Database\\Seeders;')
lines.append('')
lines.append('use App\\Models\\Kios;')
lines.append('use App\\Models\\Pemilik;')
lines.append('use App\\Models\\Sewa;')
lines.append('use App\\Models\\Tagihan;')
lines.append('use App\\Models\\User;')
lines.append('use Carbon\\Carbon;')
lines.append('use Illuminate\\Database\\Seeder;')
lines.append('use Illuminate\\Support\\Facades\\Hash;')
lines.append('')
lines.append('/**')
lines.append(' * Seeder Data Tenant Real (886 tenant) dari Plaza Kebun Sayur Balikpapan')
lines.append(' * Sumber: Data Kios BY LEGAL update 26 April 2025 (Sheet Lt1, Lt2, Lt3)')
lines.append(' * Jalankan: php artisan db:seed --class=RealTenantSeeder')
lines.append(' */')
lines.append('class RealTenantSeeder extends Seeder')
lines.append('{')
lines.append('    private string $passwordHash;')
lines.append('')
lines.append('    public function __construct()')
lines.append('    {')
lines.append("        $this->passwordHash = Hash::make('password123');")
lines.append('    }')
lines.append('')
lines.append('    public function run(): void')
lines.append('    {')
lines.append("        $this->command->info('Seeding Real Tenant Data (886 tenants from Lt1+Lt2+Lt3)...');")
lines.append('')
lines.append('        $tenants = [')

for t in tenants:
    nama   = php_str(t['nama'])
    kios   = php_str(t['kios'])
    telp   = php_str(t['telp'])
    ktp    = php_str(t['ktp'])
    alamat = php_str(t['alamat'])
    usaha  = php_str(t['jenis_usaha'])
    uname  = php_str(t['username'])
    lantai = t['lantai']
    lines.append(f"            ['nama'=>'{nama}','kios'=>'{kios}','telp'=>'{telp}','ktp'=>'{ktp}','alamat'=>'{alamat}','usaha'=>'{usaha}','username'=>'{uname}','lantai'=>{lantai}],")

lines.append('        ];')
lines.append('')
lines.append('        $tarif   = 750000.00;')
lines.append('        $mulai   = Carbon::now()->subMonths(6)->startOfMonth();')
lines.append('        $created = 0;')
lines.append('        $skipped = 0;')
lines.append('')
lines.append('        foreach ($tenants as $data) {')
lines.append("            $user = User::firstOrCreate(")
lines.append("                ['Username' => $data['username']],")
lines.append('                [')
lines.append("                    'Id_roles'     => 2,")
lines.append("                    'Password'     => $this->passwordHash,")
lines.append("                    'sub_role'     => 'tenant',")
lines.append("                    'status_aktif' => 1,")
lines.append("                    'nama_lengkap' => $data['nama'],")
lines.append("                    'email'        => $data['username'] . '@bunsay.id',")
lines.append('                ]')
lines.append('            );')
lines.append('')
lines.append("            $pemilik = Pemilik::firstOrCreate(")
lines.append("                ['Id_User' => $user->Id_user],")
lines.append('                [')
lines.append("                    'Nama'       => $data['nama'],")
lines.append("                    'No_Telepon' => $data['telp'] ?: null,")
lines.append("                    'No_KTP'     => $data['ktp']  ?: null,")
lines.append("                    'Alamat'     => $data['alamat'],")
lines.append('                ]')
lines.append('            );')
lines.append('')
lines.append("            $kios = Kios::firstOrCreate(")
lines.append("                ['No_Kios' => $data['kios']],")
lines.append("                ['Lantai' => $data['lantai'], 'Ukuran' => '4x4 m\u00b2', 'Status' => 'Terisi']")
lines.append('            );')
lines.append("            if ($kios->Status !== 'Terisi') $kios->update(['Status' => 'Terisi']);")
lines.append('')
lines.append("            $sewaAda = Sewa::where('Id_Pemilik', $pemilik->Id_Pemilik)")
lines.append("                ->where('Id_Kios', $kios->Id_Kios)->exists();")
lines.append("            if ($sewaAda) { $skipped++; continue; }")
lines.append('')
lines.append("            $sewa = Sewa::create([")
lines.append("                'Id_Pemilik'      => $pemilik->Id_Pemilik,")
lines.append("                'Id_Kios'         => $kios->Id_Kios,")
lines.append("                'Jenis_Usaha'     => $data['usaha'],")
lines.append("                'Tanggal_Mulai'   => $mulai->toDateString(),")
lines.append("                'Tanggal_Selesai' => $mulai->copy()->addYear()->toDateString(),")
lines.append("                'Keterangan'      => 'Data real tenant Plaza Kebun Sayur Balikpapan',")
lines.append("                'Status'          => 'Aktif',")
lines.append('            ]);')
lines.append('')
lines.append('            for ($m = 0; $m < 6; $m++) {')
lines.append('                $tDate  = $mulai->copy()->addMonths($m);')
lines.append('                $isLast = ($m === 5);')
lines.append('                $tagihan = Tagihan::create([')
lines.append("                    'Id_Sewa'          => $sewa->Id_Sewa,")
lines.append("                    'Periode'          => $tDate->format('Y-m'),")
lines.append("                    'Jatuh_Tempo'      => $tDate->copy()->day(12)->format('Y-m-d'),")
lines.append("                    'Tarif_Sewa'       => $tarif,")
lines.append("                    'Hutang_Tunggakan' => 0.00,")
lines.append("                    'Total_Tagihan'    => $tarif,")
lines.append("                    'Sisa_Tagihan'     => $isLast ? $tarif : 0.00,")
lines.append("                    'Status_Tagihan'   => $isLast ? 'Belum Bayar' : 'Lunas',")
lines.append('                ]);')
lines.append('                if (!$isLast) {')
lines.append('                    \\App\\Models\\Pembayaran::create([')
lines.append("                        'Id_Tagihan'            => $tagihan->Id_Tagihan,")
lines.append("                        'Tanggal_Bayar'         => $tDate->copy()->day(10)->toDateString(),")
lines.append("                        'Total_Bayar'           => $tarif,")
lines.append("                        'Metode_Bayar'          => 'Transfer',")
lines.append("                        'Bukti_Pembayaran'      => 'storage/bukti/real_'.$tagihan->Id_Tagihan.'.png',")
lines.append("                        'Verifikasi_Pembayaran' => 'Diterima',")
lines.append('                    ]);')
lines.append('                }')
lines.append('            }')
lines.append('            $created++;')
lines.append('        }')
lines.append('')
lines.append('        $this->command->info("Selesai! Dibuat: {$created} sewa baru. Dilewati: {$skipped}");')
lines.append("        \$this->command->info('Password semua tenant: password123');")
lines.append('    }')
lines.append('}')

php_code = '\n'.join(lines)
with open('RealTenantSeeder_full.php', 'w', encoding='utf-8') as f:
    f.write(php_code)
print(f'Generated! {len(tenants)} tenants, {len(lines)} lines')
